spanish_teams_A = ['FC Barcelona', 'Atlético Madrid', 'Real Madrid', 'Valencia', 'Getafe', 'Sevilla', 'RCD Espanyol',
                   'Athletic Club de Bilbao', 'Real Sociedad', 'Real Betis', 'Deportivo Alavés', 'Eibar', 'CD Leganés',
                   'Villarreal', 'Levante', 'Real Valladolid', 'Celta de Vigo', 'Girona', 'Huesca', 'Rayo Vallecano']

spanish_teams_B = ['Osasuna', 'Granada', 'Málaga', 'Albacete', 'Deportivo de la Coruña', 'Cádiz',
                   'Real Oviedo', 'Sporting de Gijón', 'Almería', 'UD Las Palmas',
                   'Alcorcón', 'Real Zaragoza', 'Tenerife', 'Numancia', 'Lugo',
                   'Gimnàstic de Tarragona', 'Córdoba', 'Reus Deportiu']

english_teams_A = ['Manchester City', 'Liverpool', 'Chelsea', 'Tottenham Hotspur', 'Arsenal', 'Manchester United',
                   'Wolverhampton Wanderers', 'Everton', 'Leicester City', 'West Ham United', 'Watford',
                   'Crystal Palace', 'Newcastle United', 'Bournemouth', 'Burnley', 'Southampton',
                   'Brighton & Hove Albion', 'Cardiff City', 'Fulham', 'Huddersfield Town']

english_teams_B = ['Leicester City', 'Ipswich Town', 'Leeds United', 'Southampton', 'West Bromwich Albion', 'Hull City',
                   'Sunderland', 'Preston North End', 'Watford', 'Norwich City', 'Blackburn Rovers', 'Cardiff City',
                   'Middlesbrough', 'Bristol City', 'Coventry City', 'Plymouth Argyle', 'Birmingham City',
                   'Swansea City', 'Stoke City', 'Millwall', 'Huddersfield Town', 'Queens Park Rangers',
                   'Sheffield Wednesday', 'Rotherham United']

all_teams = ['Real Madrid CF', 'FC Barcelona', 'Paris Saint-Germain',
             'FC Bayern Munich', 'Manchester United', 'Chelsea', 'Juventus',
             'Manchester City', 'Arsenal', 'Atlético Madrid',
             'Borussia Dortmund', 'Milan', 'Tottenham Hotspur', 'Napoli',
             'Inter', 'Liverpool', 'Roma', 'Beşiktaş JK', 'AS Monaco',
             'Bayer 04 Leverkusen', 'AS Saint-Étienne',
             'Athletic Club de Bilbao', '1. FC Köln', 'Villarreal CF',
             'FC Schalke 04', 'Olympique de Marseille', 'Atalanta',
             'RB Leipzig', 'Real Sociedad', 'Torino', 'Sporting CP',
             'Leicester City', 'Southampton', 'FC Porto', 'UD Las Palmas',
             'Olympique Lyonnais', 'Lazio', 'Genoa', 'Everton',
             'RC Celta de Vigo', 'Valencia CF', 'Sevilla FC', 'Toronto FC',
             'Borussia Mönchengladbach', 'SL Benfica', 'RCD Espanyol',
             'OGC Nice', 'Spartak Moscow', 'Swansea City', 'Sassuolo',
             'TSG 1899 Hoffenheim', 'Stoke City', 'Shakhtar Donetsk',
             'West Ham United', 'SV Werder Bremen', 'Watford', 'Galatasaray SK',
             'Lokomotiv Moscow', 'Zenit St. Petersburg', 'Bournemouth',
             'Sampdoria', 'Antalyaspor', 'Girondins de Bordeaux',
             'VfL Wolfsburg', 'New York City Football Club',
             'Hertha BSC Berlin', 'SD Eibar', 'Ajax',
             'RC Deportivo de La Coruña', 'Crystal Palace',
             'West Bromwich Albion', 'CSKA Moscow', 'Eintracht Frankfurt',
             'Real Betis Balompié', 'Fenerbahçe SK', 'Fiorentina', 'Burnley',
             'Tigres U.A.N.L.', 'San Lorenzo de Almagro',
             'Chicago Fire Soccer Club', 'Feyenoord', 'FC Krasnodar',
             'Angers SCO', 'U.N.A.M.', 'Montreal Impact', 'Chievo Verona',
             'LA Galaxy', 'Vissel Kobe', 'Bologna', 'LOSC Lille',
             'Orlando City Soccer Club', 'Atlanta United FC', 'Independiente',
             'Club Atlético Lanús', 'RSC Anderlecht', 'İstanbul Başakşehir FK',
             'Hannover 96', 'Newcastle United', 'Málaga CF', 'Trabzonspor',
             'PSV', 'FC Augsburg', 'Club Tijuana', 'VfB Stuttgart',
             'Hamburger SV', 'CD Leganés', 'Getafe CF', 'Deportivo Alavés',
             'Portland Timbers', 'Kayserispor', 'Udinese', 'Standard de Liège',
             'Alanyaspor', '1. FSV Mainz 05', 'Sparta Praha', 'FC Nantes',
             'Al Ahli', 'SC Braga', 'Brighton & Hove Albion', 'Levante UD',
             'Boca Juniors', 'Columbus Crew SC', 'Querétaro', 'Dijon FCO',
             'Olympiakos CFP', 'KRC Genk', 'FC Basel', 'Club América',
             'Montpellier Hérault SC', 'Monterrey', 'Seattle Sounders FC',
             'River Plate', 'CPD Junior Barranquilla',
             'Racing Club de Avellaneda', 'En Avant de Guingamp', 'Rangers',
             'Colorado Rapids', 'Necaxa', 'Aston Villa', 'KV Oostende',
             'Akhisar Belediyespor', 'Rubin Kazan', 'Rosario Central',
             'Ferrara (SPAL)', 'Wolverhampton Wanderers', 'Stade Rennais FC',
             'Pachuca', 'Granada CF', 'Colo-Colo', 'KAA Gent', 'Middlesbrough',
             'Toulouse FC', 'BSC Young Boys', 'FC St. Gallen',
             'Santos Futebol Clube', 'Cagliari', 'Rio Ave FC', 'Norwich City',
             'Grêmio Foot-Ball Porto Alegrense', 'Estudiantes de La Plata',
             'Cruzeiro', 'Universidad de Chile', 'Atletico Nacional Medellin',
             'FC Ufa', 'Girona CF', 'SM Caen', 'Independiente Medellín',
             'Djurgårdens IF', 'Vitória Guimarães', 'São Paulo Futebol Clube',
             'Royal Antwerp FC', 'Kaizer Chiefs', 'Fulham', 'Sunderland',
             'Huddersfield Town', 'PAOK Thessaloniki',
             'Fluminense Football Club', 'Leeds United', 'Derby County',
             'AC Ajaccio', 'Club León', 'Sociedade Esportiva Palmeiras',
             'Hellas Verona', 'Rayo Vallecano', 'Club Brugge KV',
             'Real Sporting de Gijón', 'Celtic', 'Hull City',
             'Universidad Católica', "CD O'Higgins", 'Club Atlas',
             'SC Freiburg', 'Melbourne City', 'Grupo Desportivo de Chaves',
             'Al Hilal', 'CA Osasuna', 'Perth Glory', 'Panathinaikos FC',
             'FC Utrecht', 'Club Atlético Huracán', 'Birmingham City',
             'Botafogo de Futebol e Regatas', 'Deportivo Toluca',
             'Amiens SC Football', 'Clube Atlético Paranaense', 'Göztepe',
             'FC Groningen', 'FC Ingolstadt 04', 'New England Revolution',
             'FC Red Bull Salzburg', 'Clube Atlético Mineiro', 'Crotone',
             'Banfield', 'Grasshopper Club Zürich', 'Vitesse', 'AZ Alkmaar',
             'SV Darmstadt 98', 'Avaí Futebol Clube', 'Coritiba Foot Ball Club',
             'Legia Warszawa', 'RC Strasbourg', 'Brescia',
             'Vancouver Whitecaps FC', 'Western Sydney Wanderers',
             'Guadalajara', 'Cerezo Osaka', 'CS Marítimo', 'Osmanlıspor',
             'Santos Laguna', 'Dinamo Moscow', 'Monarcas Morelia', 'Frosinone',
             'Cruz Azul', 'Real Zaragoza', 'Deportes Iquique', 'Sydney FC',
             'Brisbane Roar', 'AEK Athens', 'Colon de Santa Fe',
             'Atiker Konyaspor', 'Unión Española', 'Reading',
             'Asociacion Deportivo Cali', 'Palermo', 'FC Metz',
             'Sporting Kansas City', 'FC Seoul', 'Bursaspor',
             'Benevento Calcio', 'FC Rostov', 'Associação Atlética Ponte Preta',
             'Al Nassr', 'San Jose Earthquakes', 'Nîmes Olympique',
             'Al Ittihad', 'Godoy Cruz', 'Gimnàstic de Tarragona',
             'Philadelphia Union', 'Sport Club do Recife',
             'CD Universidad de Concepción', 'FC Paços de Ferreira',
             'New York Red Bulls', 'Club Atlético Tigre', 'FC Lorient',
             'Belgrano de Córdoba', 'Sheffield Wednesday', 'CD Tenerife',
             'SC Heerenveen', 'Independiente Santa Fe', 'Puebla',
             'Vitória Setúbal', 'FC København', 'Kalmar FF', 'CD Aves',
             "Newell's Old Boys", 'Terek Grozny', '1. FC Union Berlin',
             'Real Valladolid', 'ADO Den Haag', 'Santiago Wanderers', 'Bari',
             'Ulsan Hyundai Horang-i', '1. FC Heidenheim', 'Argentinos Juniors',
             'Brentford', 'Gençlerbirliği SK', 'FC St. Pauli',
             'Melbourne Victory', 'VfL Bochum', 'Córdoba CF',
             'Atlético Clube Goianiense', 'Kardemir Karabükspor', 'AJ Auxerre',
             'Real Oviedo', 'Vitória ', 'Arsenal Tula', 'RC Lens',
             'CF Os Belenenses', 'SK Rapid Wien', 'Everton de Viña del Mar',
             'CD Los Millionarios Bogota', 'GwangJu FC', 'Sangju Sangmu FC',
             'Jeonbuk Hyundai Motors', 'FC Dallas', 'ES Troyes AC',
             'F.B.C. Unione Venezia', 'Al Qadisiyah', 'Fortuna Düsseldorf',
             'Boavista FC', 'D.C. United', 'Medicana Sivasspor',
             'CD Once Caldas Manizales', 'FC Ural', 'Kashiwa Reysol',
             'Malmö FF', 'Cádiz C.F.', 'Portimonense SC', 'Urawa Red Diamonds',
             'UD Almería', 'AIK Solna', 'CD Huachipato', 'Estoril Praia',
             '1. FC Nürnberg', 'Pescara', 'Stade de Reims', 'Moreirense FC',
             'Empoli', 'Orlando Pirates', 'FC Anzhi Makhachkala',
             'Heracles Almelo', 'Eintracht Braunschweig', 'Cremonese',
             'CD Antofagasta', 'AS Nancy Lorraine', 'Lobos de la BUAP',
             'Suwon Samsung Bluewings', 'Defensa y Justicia', 'Ipswich Town',
             'Rosenborg BK', 'KAS Eupen', 'FC Sion', 'Adelaide United',
             'Real Salt Lake', 'FC Midtjylland', 'Minnesota Thunder',
             'AD Alcorcón', 'Al Faisaly', 'FC Tosno', 'FC Twente', 'F.C. Tokyo',
             'IF Elfsborg', 'Carpi', 'Parma', 'IFK Norrköping',
             'Unión de Santa Fe', 'Corporación Club Deportivo Tuluá',
             'Kawasaki Frontale', 'Associação Chapecoense de Futebol',
             '1. FC Kaiserslautern', 'Preston North End', 'Molde FK',
             'Bristol City', 'Brøndby IF', 'Albacete Balompié', 'GFC Ajaccio',
             'KV Kortrijk', 'Kashima Antlers', 'CD Feirense', 'Oxford United',
             'Talleres de Cordoba', 'FC Lugano', 'SV Zulte-Waregem',
             'Deportes Tolima', 'Amkar Perm', 'Kasimpaşa SK',
             'Gimnasia y Esgrima La Plata', 'Queens Park Rangers',
             'Shimizu S-Pulse', 'Aalborg BK', 'Águilas Doradas',
             'FC Lausanne-Sports', 'Tiburones Rojos de Veracruz', 'Perugia',
             'La Spezia', 'Pohang Steelers', 'FC Barcelona B',
             'Evkur Yeni Malatyaspor', 'Willem II', 'Novara',
             'Sporting Charleroi', 'FK Austria Wien', 'Gamba Osaka',
             'DSC Arminia Bielefeld', 'Nottingham Forest', 'Salernitana',
             'Vercelli', 'Śląsk Wrocław', 'Sagan Tosu', 'CD Numancia',
             'Strømsgodset IF', 'Yokohama F. Marinos', 'Cardiff City',
             'FC Sochaux-Montbéliard', 'Jeju United FC', 'Lechia Gdańsk',
             'Piast Gliwice', 'SD Huesca', 'FC Zürich', 'Heart of Midlothian',
             'Atlético Tucumán', 'BK Häcken', 'Audax Italiano',
             'Club de Deportes Temuco', 'San Luis de Quillota', 'Al Taawoun',
             'Lech Poznań', 'FC Luzern', 'Cesena', 'Chacarita Juniors',
             'Aberdeen', 'Excelsior', 'SpVgg Greuther Fürth',
             'San Martín de San Juan', 'Wisła Kraków', 'Hammarby IF',
             'Virtus Entella', 'Vegalta Sendai', 'Alianza Petrolera',
             'CD Palestino', 'KV Mechelen', 'Central Coast Mariners',
             'La Equidad', 'Avellino', 'Omiya Ardija', 'Cracovia',
             'Curicó Unido', 'CF Reus Deportiu', 'SK Brann',
             'C.D. Leonesa S.A.D.', 'US Quevilly-Rouen', 'Sporting Lokeren',
             'Houston Dynamo', 'Termalica Bruk-Bet Nieciecza', 'Tondela',
             'SV Sandhausen', 'Al Fayha', 'Jeonnam Dragons',
             'Sandefjord Fotball', 'Pogoń Szczecin', 'Östersunds FK',
             'Burton Albion', 'Al Raed', 'Jagiellonia Białystok',
             'Bahía Blanca', 'Ventforet Kofu', 'Stade Brestois 29', 'CD Lugo',
             'Korona Kielce', 'PEC Zwolle', 'MSV Duisburg', 'AFC Eskilstuna',
             'Waasland-Beveren', 'Club Atlético Patronato',
             'La Berrichonne de Châteauroux', 'SK Sturm Graz',
             'Royal Excel Mouscron', 'Júbilo Iwata', 'SønderjyskE', 'Al Shabab',
             'US Orléans Loiret Football', 'Bourg en Bresse Péronnas 01',
             'FC Nordsjælland', 'FC Thun', 'CD America de Cali', 'VVV-Venlo',
             'Charlton Athletic', 'Sevilla Atlético', 'Ternana', 'Gangwon FC',
             'IFK Göteborg', 'Odense Boldklub', 'Arsenal de Sarandí',
             'SG Dynamo Dresden', 'Bolton Wanderers', 'Plymouth Argyle',
             'Southend United', 'Vélez Sarsfield', 'Daegu FC',
             'Sanfrecce Hiroshima', 'Odds BK', 'Aarhus GF', 'Blackburn Rovers',
             'Lyngby BK', 'FC Erzgebirge Aue', 'Sint-Truidense VV',
             'Karlsruher SC', 'Jaguares Fútbol Club', 'Sarpsborg 08 FF',
             'Temperley', ' SSV Jahn Regensburg', 'Patriotas Boyacá FC',
             'Barnsley', 'Sandecja Nowy Sącz', 'Górnik Zabrze', 'VfL Osnabrück',
             'Valenciennes FC', 'Tours FC', 'Lorca Deportiva CF',
             'Albirex Niigata', 'Cittadella', 'Aalesunds FK', 'Deportivo Pasto',
             'Roda JC Kerkrade', 'Motherwell', 'Holstein Kiel',
             'Scunthorpe United', 'Atlético Huila', 'Wisła Płock',
             'Atlético Bucaramanga', 'Sparta Rotterdam', 'Stabæk Fotball',
             'Würzburger FV', 'VfR Aalen', 'Clermont Foot 63', 'Randers FC',
             'Vålerenga Fotball', 'Incheon United FC', 'Hibernian',
             'SCR Altach', 'Sheffield United', 'Le Havre AC', 'Walsall',
             'Chamois Niortais FC', 'Sportfreunde Lotte', 'Millwall',
             'SpVgg Unterhaching', 'FC SKA-Energiya Khabarovsk',
             'Hansa Rostock', 'Wellington Phoenix', 'Hobro IK',
             'Wigan Athletic', 'Peterborough United', 'Chemnitzer FC',
             'Grimsby Town', 'Ascoli', 'Al Fateh', 'Foggia', 'Bristol Rovers',
             '1. FC Magdeburg', 'SG Sonnenhof Großaspach', 'Bury',
             'Lillestrøm SK', 'Arka Gdynia', 'Ross County FC', 'Paris FC',
             'Bradford City', 'Hamilton Academical FC', 'Luton Town',
             'NAC Breda', 'Portsmouth', 'Zagłębie Lubin', 'Kilmarnock',
             'Hokkaido Consadole Sapporo', 'Örebro SK', 'SV Wehen Wiesbaden',
             'Coventry City', 'Milton Keynes Dons', 'Rochdale', 'FK Haugesund',
             'Dundee FC', 'Oldham Athletic', 'Ohod Club', 'Rotherham United',
             'HJK Helsinki', 'LASK Linz', 'AC Horsens', 'SC Fortuna Köln',
             'St. Johnstone FC', 'Sogndal', 'Envigado FC', 'Blackpool',
             'SC Preußen Münster', 'Hallescher FC', 'Ettifaq FC',
             'Crawley Town', 'Exeter City', 'AFC Wimbledon', 'Doncaster Rovers',
             'IK Sirius', 'Jönköpings Södra IF', 'Rot-Weiß Erfurt',
             'Notts County', 'SV Mattersburg', 'Viking FK', 'Cambridge United',
             'Tigres FC', 'Mansfield Town', 'SV Meppen', 'Tromsø IL',
             'Swindon Town', 'Werder Bremen II', 'FC Admira Wacker Mödling',
             'SC Paderborn 07', 'Partick Thistle F.C.', 'Silkeborg IF',
             'Al Batin', 'Colchester United', 'FSV Zwickau', 'Crewe Alexandra',
             'Northampton Town', 'Kristiansund BK', 'Lincoln City', 'Dundalk',
             'Wycombe Wanderers', 'Yeovil Town', 'GIF Sundsvall',
             'FC Carl Zeiss Jena', "St. Patrick's Athletic", 'Fleetwood Town',
             'Wolfsberger AC', 'Cork City', 'Gillingham', 'SKN St. Pölten',
             'Carlisle United', 'Chesterfield', 'Newcastle Jets', 'Morecambe',
             'Port Vale', 'Newport County', 'Shrewsbury', 'Accrington Stanley',
             'Forest Green', 'Bohemian FC', 'Cheltenham Town', 'Barnet',
             'Halmstads BK', 'Shamrock Rovers', 'Derry City', 'Stevenage',
             'Finn Harps', 'FC Helsingør', 'Sligo Rovers', 'Bray Wanderers',
             'Limerick FC', 'Galway United', 'Drogheda United']
import os
file_path = os.path.join(os.getcwd(),'data')
file_complete = os.path.join(file_path,'CompleteDataset.csv')

import pandas as pd
# Lee el archivo CSV en un DataFrame de pandas
df = pd.read_csv(file_complete)

# Filtra el DataFrame para mantener solo las filas donde 'club' está en alguna de las listas
df_filtrado = df[df['Club'].isin(spanish_teams_A + spanish_teams_A + english_teams_A + english_teams_B)]


print('hola')
